stages:
  - deploy

variables:
  REPOSITORY: unifyid/apola-dl-notebook
  VENDOR: UnifyID

before_script:
  - virtualenv env
  - ./env/bin/pip install --upgrade git+ssh://git@git.unify.id/UnifyID/dockerhelper.git

deploy_gpu:
  stage: deploy
  only:
    - master
  script:
    - ./env/bin/dockerhelper build --tag gpu Dockerfile.gpu
    - ./env/bin/dockerhelper push --tag gpu -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD Dockerfile.gpu
  tags:
    - shell

deploy_cpu:
  stage: deploy
  only:
    - master
  script:
    - ./env/bin/dockerhelper build --tag cpu Dockerfile.cpu
    - ./env/bin/dockerhelper push --tag cpu -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD Dockerfile.cpu
  tags:
    - shell

deploy_latest:
  stage: deploy
  only:
    - master
  script:
    - ./env/bin/dockerhelper build --tag latest Dockerfile.cpu
    - ./env/bin/dockerhelper push --tag latest -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD Dockerfile.cpu
  tags:
    - shell